### ISSUE TITLE
Feature Request: Competition List Improvements

### ISSUE THREAD

**Issue by VictorianVader** [emperorshammer/issues-incoming-queue#120]
A couple feature requests related to the list of competitions:

1. Currently, competitions are moved from Pending to Current as soon as they are approved, regardless of when the competition is actually supposed to start.  Please differentiate between competitions that are approved but not active and approved and currently active.
- Split up the "Current Competitions" into separate lists: "Approved - Pending" and "Approved - Active" (or something with a similar result).
OR
- Change "Current Competitions" to "Approved Competitions" and add a column for the official start date.

2. Make the competition list columns sortable.  Currently the competitions are automatically sorted by ID number.  It would be nice to be able to sort by competition title, units involved, and time remaining.

**Comment by turtlexiv** [comment]
We'll still be doing some more changes with this, but I've implemented a few that are now live on the site.

On down the road we have a plan for improving some aspects of the competition system, so that will be a better time to deal with the sorting (and filtering, since 'units involved' will become a field for actually tagging units).
