### ISSUE TITLE
Eligibility for IU certificates interface

### ISSUE THREAD

**Issue by SylasPitt** [emperorshammer/issues-incoming-queue#213]
Would be neat if I could have an eligibility board to see which members are eligible for qualifications that they haven't claimed. Maybe also having the permission to grant them through that interface to the student who might not be aware that they have to manually claim those qualifications. 

Mainly meant for the Certificate level qualification, as I'm sure those aiming for Graduates or higher have already figured it out.

**Comment by turtlexiv** [comment]
Because of the way qualification checking is implemented, this might be a bit of a pain. I'll need to check further to figure out for sure. (Basically the code does a "live" comparison of the current requirement set to what the member has on their record; because the complex structure we built for the requirement sets it takes a lot of queries to check just one qualification.)

As a possible alternative or addition, we could at least display on course information pages that they are part of a qualification requirement track. This might help people notice that courses they might be taking are part of a qualification, and then access that qualification to learn more and see which requirement's they've already achieved.
