### ISSUE TITLE
TTT3 - Unable to select Ship/Wing/Squadron for inactive members

### ISSUE THREAD

**Issue by jonathon-green** [emperorshammer/issues-incoming-queue#31]
TTT3 allows you to select Ship, Wing and Squadron when creating a pilots uniform. These options are used for post dated uniforms or pre-emptively updating a uniform, but not available for pilots in the Reserves.

It might make sense for the M/FRG Phoenix to be represented in the fleet.json file.

**Comment by turtlexiv** [comment]
I'm not clear what the problem is. You can create a uniform for a reservist either by importing, or manually by selecting the appropriate rank with the "line rank" or "flag rank" button. Can you elaborate?

**Comment by SmTaUcM** [comment]
Ship / Wing / Squadron selection dictates the uniform's trim colour, collar numerals and Squadron patches.

A reservist uniform does not include these details and as such the Line Rank or Flag Rank option should be selected instead. 
The import functionality will automatically select this setting for you. Which in turn also inhibits position selection as reservists do not hold positions.
As the M/FRG Phoenix does not have a trim colour, I can see no value in adding it to the fleet json file.

**Comment by jonathon-green** [comment]
If you're making a uniform for someone whose in the reserves, you don't have options to change their Ship / Wing / Squadron.

If you're making a uniform for someone not in the reserves, you can change their Ship / Wing / Squadron. Ergo, you can make uniforms for people pre or post transfers, _unless_ they're currently in the reserves.

This is inconsistent and the work around is importing an active fleet member, changing the Ship / Wing / Squadron if necessary, then manually copying all medals and other details over.

If the M/FRG was implemented in the same way as other ships, I don't think this problem would exist.

**Comment by SmTaUcM** [comment]
If your making a uniform for someone in the reserves, you don't have options to change their Ship / Wing / Squadron because the "line rank" or "flag rank" option is selected within the "Position and Rank" tab. You must first select a Position from this tab, which then unlocks the "Wing and Squadron" tab options. You cannot be assigned to a Ship, Wing or a Squadron without having a position. This is an intentional feature to prevent you from making an invalid uniform.

Rather than importing an active fleet member, changing the Ship / Wing / Squadron if necessary, then manually copying all medals and other details over, the proper process should be:

Open TTT3.
Go to "Import" tab.
Import reservist's profile.
Go to "Position and Rank" tab.
Select your desired position followed by your current rank.
Go to "Wing and Squadron" tab.
Select your desired Wing, Ship and Squadron.
Click "Dress Uniform" button and proceed to Ray Trace your uniform.

No manual copying of medals is necessary this way. 
This is the proper process that a reservist wanting to make a pre or post transfer should follow.

The only other way would be to add the M/FRG Phoenix as a ship to TTT3 as well as adding Reservist (RSV) as a position which is not currently a planned feature.

**Comment by jonathon-green** [comment]
I see now. For some reason it wasn't obvious to me that the Wing and Squadron tab had a dependency on the Position/Rank tab.

Thank you for the help.
