### ISSUE TITLE
SP killboard and Gonk/ATR not matching

### ISSUE THREAD

**Issue by ColoDelste** [emperorshammer/issues-incoming-queue#78]
As it says on the tin. Website may not have pulled info from ATR properly/completely? It's short 4 TIE missions, which is likely the ones from 27/03

![GONK](https://user-images.githubusercontent.com/99576682/160352756-7c9a2ab1-7a92-4c0a-8e21-8212d14845b6.jpg)
![SPKill](https://user-images.githubusercontent.com/99576682/160352762-e1682a85-b4b2-4a64-b653-06db2e511302.jpg)

**Comment by SmTaUcM** [comment]
No bug here. This is because you have flown TIE-TC 19 (4 Missions) twice this year. Once on the 13th Feb 2022 and again on the 8th March 2022.

The SP kill board only allows the the flying of a SP battle/mission once in a 12 month period to qualify.

As it states at the top of the SP killboard:
**_"While the same mission can be flown multiple times for other purposes, it will only count once per year."_**

**Comment by ColoDelste** [comment]
Oh. That would do it. That's what I get for trying to improve my score for TCiB :P
